server:
  port: 8090

spring:
  profiles:
    #开发改"dev" 推送线上改"prod"
    active: @profileActive@
  application:
    name: oio-core
  datasource:
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.dbfmp.user.center.server.mapper: debug