spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.15:8848
  main:
    allow-bean-definition-overriding: true

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://192.168.3.15
  scan:
    base-packages: indi.dbfmp.oio.auth
  cloud:
    subscribed-services: oio-core